# Generated by Django 3.2.6 on 2022-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачен'),
        ),
    ]
